# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Test of calling a Fortran 77 Function
NULL

#' Test of calling a Fortran Function
#'
#' @param x A numeric vector
#' @return A transformed numeric vector
#' @examples
#' test_function(0:9)
test_function <- function(x) {
    .Call(`_mixedlang_test_function`, x)
}

facto <- function(n) {
    .Call(`_mixedlang_facto`, n)
}

